### ISSUE TITLE
Explore adding letters or other visual treatments to notes for learning

### ISSUE THREAD

**Issue by chrisglein** [brewingcode/shanties#2]
Intro music books may put the note names on top like this:
![image](https://github.com/brewingcode/shanties/assets/26607885/9a487634-3e2d-494b-b4d7-b9662691101e)

This would be handy to have as mode, although I don't see it in the abcjs options. So... gotta build it.

The notes all have `data-name` set, which would provide a way to CSS select the items. One easy option is to colorize them:

```css
path[data-name="A"],
path[data-name="A,"],
path[data-name="a"]{
    color: red;
}
path[data-name="B"],
path[data-name="B,"],
path[data-name="b"]{
    color: orange;
}
path[data-name="C"],
path[data-name="C,"],
path[data-name="c"]{
    color: yellowgreen;
}
path[data-name="D"],
path[data-name="D,"],
path[data-name="d"]{
    color: green;
}
path[data-name="E"],
path[data-name="E,"],
path[data-name="e"]{
    color: blue;
}
path[data-name="F"],
path[data-name="F,"],
path[data-name="f"]{
    color: indigo;
}
path[data-name="G"],
path[data-name="G,"],
path[data-name="g"]{
    color: darkviolet;
}
```

![image](https://github.com/brewingcode/shanties/assets/26607885/9d25c351-88bd-48ff-966f-9cb2f69d3f79)

Done with rainbow colors because [that's the whole reason there are 7 colors in the rainbow even though indigo is bullshit](https://en.wikipedia.org/wiki/ROYGBIV).

It should be possible to add a psuedo element with similar selectors, but something about having this embedded in the SVG grouping has it not render and I haven't figured out yet:

```css
path[data-name="E"]:before {
    content: 'e';
}
```

Maybe [this](https://stackoverflow.com/questions/62994239/before-pseudo-element-not-showing-up-on-path-element) is the reason ("you can't have a before pseudo element for a path")? I don't know _why_? And the psuedo element is created, but not placed/rendered.
